version: "3.8"

services:
  pm_project_management:
    build: .
    ports:
      - "8082:8080"  # Expone el puerto 8080 del contenedor como 8082 en el host
    depends_on:
      - pm_user_management_db
    env_file:
      - .env  # Carga las variables de entorno desde .env

  pm_user_management_db:
    image: postgres:13
    env_file:
      - .env  # Carga las variables de entorno desde .env
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: